setwd("/Users/hugospersonalcenter")
getwd()
list.files()
setwd("Documents")
getwd()
list.files()
setwd("Brown")
getwd()
list.files()
setwd("Week1")
getwd()
list.files()

data()
data("occupationalStatus")
save("occupationalStatus", file = "occupationalStatus_summary.RData")
getwd()
list.files()
rm(occupationalStatus)
load("occupationalStatus_summary.RData")
